flowchart TD
    %% Style (Vermelho  PK, Azul  atributos comuns)
    classDef pk stroke:#f00,stroke-width:2px,fill:#fff,color:#000;
    classDef attr stroke:#00f,stroke-width:2px,fill:#fff,color:#000;
    classDef fk stroke:#0a0,stroke-width:2px,fill:#fff,color:#000;
    classDef rel fill:#555,stroke:#fff,stroke-width:1px;

    %% ================= ENTIDADES =================
    Evento[tbl_evento]
    PapelParticipacao[tbl_papel_participacao]
    Trilha[tbl_trilha]
    Questao[tbl_questao]
    FormularioAvaliacao[tbl_formulario_avaliacao]
    Pessoa[tbl_pessoa]
    Instituicao[tbl_instituicao]
    Decisao[tbl_decisao]
    Revisao[tbl_revisao]
    Topico[tbl_topico]
    Submissao[tbl_submissao]
    AtribuicaoRevisao[tbl_atribuicao_revisao]
    AtribuicaoVersao[tbl_atribuicao_versao]
    VersaoSubmissao[tbl_versao_submissao]
    FinalidadeAlteracao[tbl_finalidade_alteracao]
    Edicao[tbl_edicao]

    %% NOVAS ENTIDADES - FILIPE
    RespostaQuestao[tbl_resposta_questao]
    ParticipanteEdicao[tbl_participante_edicao]
    RespostaQuestao[tbl_resposta_questao]
    %% conflito de interesse
    ConflitoInteresse[tbl_conflito_interesse]
    %% indicaçao de interesse (bidding como ta nos requisitos) do revisor pelos artigos
    PreferenciaRevisao[tbl_preferencia_revisao]
    %% relacionamento N:M entre submissao e topico
    SubmissaoTopico[tbl_submissao_topico]
    %% relacionamento N:M entre pessoas e topicos
    PessoaTopico[tbl_pessoa_topico]

    %% ================= RELACIONAMENTOS =================
    %% RF15 - caso uma pessoa opte por revisar uma submissao de uma trilha, ela recebe papel revisor também?
    Rel_PapelParticipacao_Trilha{participa_como}:::rel
    Rel_Edicao_Trilha{contem}:::rel
    %% (1, 1) ou (1, N) Trilhas podem ser "reutilizadas" entre as edições?
    Rel_Edicao_Evento{possui}:::rel
    Rel_Evento_Pessoa{coordena}:::rel
    Rel_Instituicao_Pessoa{rel}:::rel
    %% Tabela N:M ->  (0, N) ou (1, N)
    %% Uma instituição deve estar obrigatoriamente associada a uma pessoa para existir no BD?
    Rel_Decisao_Pessoa{rel2}:::rel
    Rel_AtribuicaoRevisao_Pessoa{revisa}:::rel
    %% Pelo RF13, uma revisão pode ter (1,n) revisores, mas existe ce_revisor
    Rel_VersaoSubmissao_Pessoa{is_responsavel_por}:::rel
    Rel_AtribuicaoVersao_Pessoa{rel3}:::rel
    Rel_Revisao_AtribuicaoRevisao{deve_revisar}:::rel
    %% RF18 - deve estar no MER ou só no código?
    Rel_Submissao_AtribuicaoRevisao{atribuivel_a}:::rel
    %% deveria haver relação com expertise de pessoa com topico?
    Rel_Submissao_AtribuicaoVersao{autoria}:::rel
    Rel_VersaoSubmissao_FinalidadeAlteracao{tem_como_finalidade}:::rel
    %% Alteração de autores seria a nível de implementação
    %% Prazo para elementos tirar dúvida se poderia ser uma entidade ou atributos de entidades existentes
    Rel_VersaoSubmissao_Submissao{contem2}:::rel
    Rel_Topico_Submissao{abrange}:::rel
    Rel_Topico_Pessoa{expertise_em}:::rel
    Rel_Revisao_FormularioAvaliacao{utilizado}:::rel
    Rel_Trilha_FormularioAvaliacao{possui}:::rel
    Rel_Questao_FormularioAvaliacao{composto_por}:::rel
    Rel_Submissao_Trilha{pertence}:::rel
    %% Entender melhor relações entre tópicos-trilha e submissão-trilha

    %% NOVOS RELACIONAMENTOS - FILIPE
    Rel_Revisao_Resposta{gera_resposta}:::rel
    Rel_Resposta_Questao{responde_a}:::rel
    Rel_Pessoa_Participante{exerce_papel}:::rel
    Rel_Edicao_Participante{ocorreu_em}:::rel
    Rel_Papel_Participante{definido_por}:::rel
    Rel_Pessoa_Participante{exerce_papel}:::rel
    Rel_Edicao_Participante{ocorreu_em}:::rel
    Rel_Papel_Participante{definido_por}:::rel
    Rel_Revisao_Resposta{gera_resposta}:::rel
    Rel_Resposta_Questao{responde_a}:::rel
    Rel_Pessoa_Conflito{declara_conflito}:::rel
    Rel_Submissao_Conflito{possui_impedimento}:::rel
    Rel_Pessoa_Preferencia{indica_interesse}:::rel
    Rel_Submissao_Preferencia{alvo_preferencia}:::rel
    Rel_Submissao_SubTopico{classificada_em}:::rel
    Rel_Topico_SubTopico{categoriza}:::rel
    Rel_Pessoa_PessoaTopico{tem_expertise}:::rel
    Rel_Topico_PessoaTopico{dominio_em}:::rel


    %% ================= LIGAÇÕES ENTIDADE <-> RELACIONAMENTO =================
    PapelParticipacao ---|1,n| Rel_PapelParticipacao_Trilha ---|1,1| Trilha
    Edicao ---|1,n| Rel_Edicao_Trilha ---|1,1| Trilha
    Edicao ---|1,1| Rel_Edicao_Evento ---|1,n| Evento
    Evento ---|1,1| Rel_Evento_Pessoa ---|1,n| Pessoa
    Instituicao ---|0,n| Rel_Instituicao_Pessoa ---|0,n| Pessoa
    Decisao ---|0,n| Rel_Decisao_Pessoa ---|0,n| Pessoa
    AtribuicaoRevisao ---|1,1| Rel_AtribuicaoRevisao_Pessoa ---|1,n| Pessoa
    VersaoSubmissao ---|1,n| Rel_VersaoSubmissao_Pessoa ---|1,n| Pessoa
    AtribuicaoVersao ---|0,n|  Rel_AtribuicaoVersao_Pessoa ---|0,n|  Pessoa
    Revisao ---|0,n| Rel_Revisao_AtribuicaoRevisao ---|0,n| AtribuicaoRevisao
    Submissao ---|1,n| Rel_Submissao_AtribuicaoRevisao ---|1,1| AtribuicaoRevisao
    Submissao ---|0,n| Rel_Submissao_AtribuicaoVersao ---|0,n| AtribuicaoVersao
    VersaoSubmissao ---|1,1| Rel_VersaoSubmissao_FinalidadeAlteracao ---|1,1| FinalidadeAlteracao
    VersaoSubmissao ---|1,1| Rel_VersaoSubmissao_Submissao ---|1,n| Submissao
    Topico ---|1,n| Rel_Topico_Submissao ---|1,n| Submissao
    Topico ---|1,n| Rel_Topico_Pessoa ---|1,n| Pessoa
    Revisao ---|1,1| Rel_Revisao_FormularioAvaliacao ---|1,n| FormularioAvaliacao
    Trilha ---|1,1| Rel_Trilha_FormularioAvaliacao ---|1,n| FormularioAvaliacao
    Questao ---|1,n| Rel_Questao_FormularioAvaliacao ---|1,n| FormularioAvaliacao
    Submissao ---|1,1| Rel_Submissao_Trilha ---|0,n| Trilha
    %% NOVAS LIGAÇÕES - FILIPE
    Revisao ---|1,n| Rel_Revisao_Resposta ---|1,1| RespostaQuestao
    RespostaQuestao ---|1,1| Rel_Resposta_Questao ---|1,1| Questao
    Pessoa ---|1,n| Rel_Pessoa_Participante ---|1,1| ParticipanteEdicao
    Edicao ---|1,n| Rel_Edicao_Participante ---|1,1| ParticipanteEdicao
    PapelParticipacao ---|1,n| Rel_Papel_Participante ---|1,1| ParticipanteEdicao
    Revisao ---|1,n| Rel_Revisao_Resposta ---|1,1| RespostaQuestao
    RespostaQuestao ---|1,1| Rel_Resposta_Questao ---|1,1| Questao
    Pessoa ---|0,n| Rel_Pessoa_Conflito ---|1,1| ConflitoInteresse
    Submissao ---|0,n| Rel_Submissao_Conflito ---|1,1| ConflitoInteresse
    Pessoa ---|0,n| Rel_Pessoa_Preferencia ---|1,1| PreferenciaRevisao
    Submissao ---|0,n| Rel_Submissao_Preferencia ---|1,1| PreferenciaRevisao
    Submissao ---|1,n| Rel_Submissao_SubTopico ---|1,1| SubmissaoTopico
    Topico ---|1,n| Rel_Topico_SubTopico ---|1,1| SubmissaoTopico
    Pessoa ---|0,n| Rel_Pessoa_PessoaTopico ---|1,1| PessoaTopico
    Topico ---|0,n| Rel_Topico_PessoaTopico ---|1,1| PessoaTopico

    %% ================= ATRIBUTOS (Elipses) =================
    %% Atributos tbl_evento
    PK_Evento([cp_id_evento]):::pk
    Attr_NmEvento([nm_evento]):::attr
    Attr_SgEvento([sg_evento]):::attr
    Attr_DsEvento([ds_evento]):::attr
    FK_Evento_Coordenador([ce_coordenador]):::fk

    Evento --- PK_Evento
    Evento --- Attr_NmEvento
    Evento --- Attr_SgEvento
    Evento --- Attr_DsEvento
    Evento --- FK_Evento_Coordenador

    %% Atributos tbl_papel_participacao
    PK_PapelPessoa([cp_id_papel_pessoa]):::pk
    Attr_DsParticipacao([ds_participacao]):::attr
    Attr_NmTituloParticipacao([nm_titulo_participacao]):::attr

    PapelParticipacao --- PK_PapelPessoa
    PapelParticipacao --- Attr_DsParticipacao
    PapelParticipacao --- Attr_NmTituloParticipacao

    %% Atributos tbl_trilha
    PK_Trilha([cp_id_trilha]):::pk
    FK_Trilha_Edicao([ce_edicao]):::fk
    Attr_TpAnonimato([tp_anonimato]):::attr
    Attr_NrRevisoresDesejado([nr_revisores_desejado]):::attr
    Attr_NmTrilha([nm_trilha]):::attr
    Attr_DsTrilha([ds_trilha]):::attr
    Attr_QtdRevisoesMaxPorPessoa([qtd_revisoes_max_por_pessoa]):::attr

    Trilha --- PK_Trilha
    Trilha --- FK_Trilha_Edicao
    Trilha --- Attr_TpAnonimato
    Trilha --- Attr_NrRevisoresDesejado
    Trilha --- Attr_NmTrilha
    Trilha --- Attr_DsTrilha
    Trilha --- Attr_QtdRevisoesMaxPorPessoa

    %% Atributos tbl_questao
    PK_Questao([cp_id_questao]):::pk
    Attr_OrdemApresentacao([ordem_apresentacao]):::attr
    Attr_Peso([peso]):::attr
    Attr_Obrigatoriedade([obrigatoriedade]):::attr
    Attr_TipoResposta([tipo_resposta]):::attr
    Attr_Status([status]):::attr

    Questao --- PK_Questao
    Questao --- Attr_OrdemApresentacao
    Questao --- Attr_Peso
    Questao --- Attr_Obrigatoriedade
    Questao --- Attr_TipoResposta
    Questao --- Attr_Status

    %% Atributos tbl_formulario_avaliacao
    PK_Formulario([cp_id_formulario]):::pk
    FK_Formulario_Trilha([ce_trilha]):::fk
    Attr_NmFormulario([nm_formulario]):::attr
    Attr_NrVersao([nr_versao]):::attr
    Attr_DtInicioVigencia([dt_inicio_vigencia]):::attr
    Attr_DtFimVigencia([dt_fim_vigencia]):::attr

    FormularioAvaliacao --- PK_Formulario
    FormularioAvaliacao --- FK_Formulario_Trilha
    FormularioAvaliacao --- Attr_NmFormulario
    FormularioAvaliacao --- Attr_NrVersao
    FormularioAvaliacao --- Attr_DtInicioVigencia
    FormularioAvaliacao --- Attr_DtFimVigencia

    %% Atributos tbl_pessoa
    PK_Pessoa([cp_id_pessoa]):::pk
    Attr_NmPessoa([nm_pessoa]):::attr
    Attr_EmailPrincipal([email_principal]):::attr
    Attr_CdOrcid([cd_orcid]):::attr
    Attr_PaisPessoa([pais_pessoa]):::attr

    Pessoa --- PK_Pessoa
    Pessoa --- Attr_NmPessoa
    Pessoa --- Attr_EmailPrincipal
    Pessoa --- Attr_CdOrcid
    Pessoa --- Attr_PaisPessoa

    %% Atributos tbl_instituicao
    PK_Instituicao([cp_id_instituicao]):::pk
    Attr_PaisInstituicao([pais_intituicao]):::attr
    Attr_NmInstituicao([nm_instituicao]):::attr
    Attr_SgInstituicao([sg_instituicao]):::attr
    Attr_CidadeInstituicao([cidade_instituicao]):::attr
    Attr_UfInstituicao([uf_instituicao]):::attr

    Instituicao --- PK_Instituicao
    Instituicao --- Attr_PaisInstituicao
    Instituicao --- Attr_NmInstituicao
    Instituicao --- Attr_SgInstituicao
    Instituicao --- Attr_CidadeInstituicao
    Instituicao --- Attr_UfInstituicao

    %% Atributos tbl_decisao
    PK_Decisao([cp_id_decisao]):::pk
    FK_Decisao_Submissao([ce_submissao]):::fk
    Attr_ResultadoDecisao([resultado_decisao]):::attr
    Attr_DtDecisao([dt_decisao]):::attr
    FK_Decisao_Responsavel([ce_responsavel]):::fk
    Attr_DsJustificativa([ds_justificativa]):::attr

    Decisao --- PK_Decisao
    Decisao --- FK_Decisao_Submissao
    Decisao --- Attr_ResultadoDecisao
    Decisao --- Attr_DtDecisao
    Decisao --- FK_Decisao_Responsavel
    Decisao --- Attr_DsJustificativa

    %% Atributos tbl_revisao
    PK_Revisao([cp_id_revisao]):::pk
    Attr_DtInicio([dt_inicio]):::attr
    FK_Revisao_Formulario([ce_formulario]):::fk
    FK_Revisao_Atribuicao([ce_atribuicao]):::fk
    Attr_DtSubmissao([dt_submissao]):::attr
    Attr_StatusRevisao([status_revisao]):::attr

    Revisao --- PK_Revisao
    Revisao --- Attr_DtInicio
    Revisao --- FK_Revisao_Formulario
    Revisao --- FK_Revisao_Atribuicao
    Revisao --- Attr_DtSubmissao
    Revisao --- Attr_StatusRevisao

    %% Atributos tbl_topico
    PK_Topico([cp_id_topico]):::pk
    FK_Topico_Trilha([ce_trilha]):::fk
    Attr_NmTopico([nm_topico]):::attr
    Attr_DsTopico([ds_topico]):::attr

    Topico --- PK_Topico
    Topico --- FK_Topico_Trilha
    Topico --- Attr_NmTopico
    Topico --- Attr_DsTopico

    %% Atributos tbl_submissao
    PK_Submissao([cp_id_submissao]):::pk
    FK_Submissao_Trilha([ce_trilha]):::fk
    Attr_ResumoSubmissao([resumo_submissao]):::attr
    Attr_DtRegistro([dt_registro]):::attr
    Attr_IdiomaSubmissao([idioma_submissao]):::attr
    Attr_StatusSubmissao([status_submissao]):::attr
    Attr_TituloSubmissao([titulo_submissao]):::attr

    Submissao --- PK_Submissao
    Submissao --- FK_Submissao_Trilha
    Submissao --- Attr_ResumoSubmissao
    Submissao --- Attr_DtRegistro
    Submissao --- Attr_IdiomaSubmissao
    Submissao --- Attr_StatusSubmissao
    Submissao --- Attr_TituloSubmissao

    %% Atributos tbl_atribuicao_revisao
    PK_AtribuicaoRevisao([cp_id_atribuicao_revisao]):::pk
    FK_AtribuicaoRevisao_Submissao([ce_submissao]):::fk
    FK_AtribuicaoRevisao_Revisor([ce_revisor]):::fk
    Attr_StatusAtribuicaoRevisao([status_atribuicao]):::attr
    Attr_DtRespostaRevisao([dt_resposta]):::attr
    Attr_TpOrigemAtribuicaoRevisao([tp_origem_atribuicao]):::attr
    Attr_DtAtribuicaoRevisao([dt_atribuicao]):::attr

    AtribuicaoRevisao --- PK_AtribuicaoRevisao
    AtribuicaoRevisao --- FK_AtribuicaoRevisao_Submissao
    AtribuicaoRevisao --- FK_AtribuicaoRevisao_Revisor
    AtribuicaoRevisao --- Attr_StatusAtribuicaoRevisao
    AtribuicaoRevisao --- Attr_DtRespostaRevisao
    AtribuicaoRevisao --- Attr_TpOrigemAtribuicaoRevisao
    AtribuicaoRevisao --- Attr_DtAtribuicaoRevisao

    %% Atributos tbl_atribuicao_versao
    PK_AtribuicaoVersao([cp_id_atribuicao_versao]):::pk
    FK_AtribuicaoVersao_Submissao([ce_submissao]):::fk
    FK_AtribuicaoVersao_Revisor([ce_revisor]):::fk
    Attr_DtAtribuicaoVersao([dt_atribuicao]):::attr
    Attr_DtRespostaVersao([dt_resposta]):::attr
    Attr_TpOrigemAtribuicaoVersao([tp_origem_atribuicao]):::attr
    Attr_StatusAtribuicaoVersao([status_atribuicao]):::attr

    AtribuicaoVersao --- PK_AtribuicaoVersao
    AtribuicaoVersao --- FK_AtribuicaoVersao_Submissao
    AtribuicaoVersao --- FK_AtribuicaoVersao_Revisor
    AtribuicaoVersao --- Attr_DtAtribuicaoVersao
    AtribuicaoVersao --- Attr_DtRespostaVersao
    AtribuicaoVersao --- Attr_TpOrigemAtribuicaoVersao
    AtribuicaoVersao --- Attr_StatusAtribuicaoVersao

    %% Atributos tbl_versao_submissao
    PK_Versao([cp_id_versao]):::pk
    FK_Versao_Submissao([ce_submissao]):::fk
    FK_Versao_ResponsavelEnvio([ce_responsavel_envio]):::fk
    Attr_NrVersaoSubmissao([nr_versao]):::attr
    FK_Versao_FinalidadeAlteracao([ce_finalidade_alteracao]):::fk
    Attr_TpVersao([tp_versao]):::attr
    Attr_DtEnvio([dt_envio]):::attr
    Attr_NmArquivo([nm_arquivo]):::attr
    Attr_DsLocalizacaoArquivo([ds_localizacao_arquivo]):::attr
    Attr_HashArquivo([hash_arquivo]):::attr

    VersaoSubmissao --- PK_Versao
    VersaoSubmissao --- FK_Versao_Submissao
    VersaoSubmissao --- FK_Versao_ResponsavelEnvio
    VersaoSubmissao --- Attr_NrVersaoSubmissao
    VersaoSubmissao --- FK_Versao_FinalidadeAlteracao
    VersaoSubmissao --- Attr_TpVersao
    VersaoSubmissao --- Attr_DtEnvio
    VersaoSubmissao --- Attr_NmArquivo
    VersaoSubmissao --- Attr_DsLocalizacaoArquivo
    VersaoSubmissao --- Attr_HashArquivo

    %% Atributos tbl_finalidade_alteracao
    PK_FinalidadeAlteracao([cp_id_finalidade_alteracao]):::pk
    Attr_DescricaoFinalidade([descricao]):::attr
    Attr_TipoFinalidade([tipo]):::attr

    FinalidadeAlteracao --- PK_FinalidadeAlteracao
    FinalidadeAlteracao --- Attr_DescricaoFinalidade
    FinalidadeAlteracao --- Attr_TipoFinalidade

    %% Atributos tbl_edicao
    PK_Edicao([cp_id_edicao]):::pk
    FK_Edicao_Evento([ce_evento]):::fk
    Attr_CrEdicao([cr_edicao]):::attr
    Attr_AnoEdicao([ano_edicao]):::attr

    Edicao --- PK_Edicao
    Edicao --- FK_Edicao_Evento
    Edicao --- Attr_CrEdicao
    Edicao --- Attr_AnoEdicao

    %% NOVOS ATRIBUTOS - FILIPE
    %% Atributos tbl_resposta_questao
    PK_RespostaQuestao([cp_id_resposta]):::pk
    FK_Resposta_Revisao([ce_revisao]):::fk
    FK_Resposta_Questao([ce_questao]):::fk
    Attr_VlResposta([vl_resposta]):::attr
    Attr_NotaQuestao([nr_nota]):::attr

    RespostaQuestao --- PK_RespostaQuestao
    RespostaQuestao --- FK_Resposta_Revisao
    RespostaQuestao --- FK_Resposta_Questao
    RespostaQuestao --- Attr_VlResposta
    RespostaQuestao --- Attr_NotaQuestao

    %% Atributos tbl_participante_edicao 
    PK_ParticipanteEdicao([cp_id_participante_edicao]):::pk
    FK_Participante_Pessoa([ce_pessoa]):::fk
    FK_Participante_Edicao([ce_edicao]):::fk
    FK_Participante_Papel([ce_papel_pessoa]):::fk
    Attr_DtInicioVigenciaPapel([dt_inicio_vigencia]):::attr
    Attr_DtFimVigenciaPapel([dt_fim_vigencia]):::attr
    Attr_StAtivo([st_ativo]):::attr

    ParticipanteEdicao --- PK_ParticipanteEdicao
    ParticipanteEdicao --- FK_Participante_Pessoa
    ParticipanteEdicao --- FK_Participante_Edicao
    ParticipanteEdicao --- FK_Participante_Papel
    ParticipanteEdicao --- Attr_DtInicioVigenciaPapel
    ParticipanteEdicao --- Attr_DtFimVigenciaPapel
    ParticipanteEdicao --- Attr_StAtivo

    %% Atributos tbl_conflito_interesse
    PK_Conflito([cp_id_conflito]):::pk
    FK_Conflito_Pessoa([ce_pessoa]):::fk
    FK_Conflito_Submissao([ce_submissao]):::fk
    Attr_TpConflito([tp_conflito]):::attr
    Attr_DtDeclaracaoConflito([dt_declaracao]):::attr

    ConflitoInteresse --- PK_Conflito
    ConflitoInteresse --- FK_Conflito_Pessoa
    ConflitoInteresse --- FK_Conflito_Submissao
    ConflitoInteresse --- Attr_TpConflito
    ConflitoInteresse --- Attr_DtDeclaracaoConflito

    %% Atributos tbl_preferencia_revisao
    PK_Preferencia([cp_id_preferencia]):::pk
    FK_Preferencia_Pessoa([ce_pessoa]):::fk
    FK_Preferencia_Submissao([ce_submissao]):::fk
    Attr_NivelInteresse([nivel_interesse]):::attr

    PreferenciaRevisao --- PK_Preferencia
    PreferenciaRevisao --- FK_Preferencia_Pessoa
    PreferenciaRevisao --- FK_Preferencia_Submissao
    PreferenciaRevisao --- Attr_NivelInteresse

    %% Atributos tbl_submissao_topico
    FK_SubTopico_Submissao([ce_submissao]):::fk
    FK_SubTopico_Topico([ce_topico]):::fk

    SubmissaoTopico --- FK_SubTopico_Submissao
    SubmissaoTopico --- FK_SubTopico_Topico

    %% Atributos tbl_pessoa_topico
    FK_PessoaTopico_Pessoa([ce_pessoa]):::fk
    FK_PessoaTopico_Topico([ce_topico]):::fk
    Attr_NivelExpertise([nivel_expertise]):::attr

    PessoaTopico --- FK_PessoaTopico_Pessoa
    PessoaTopico --- FK_PessoaTopico_Topico
    PessoaTopico --- Attr_NivelExpertise